name: AdriAPI
version: '${version}'
main: me.adrigamer2950.adriapi.AdriAPI
api-version: 1.20
author: '${author}'
description: '${description}'
website: https://github.com/Adrigamer2950/AdriAPI
load: STARTUP
folia-supported: true

commands:
  adriapi:
    description: Main command
    usage: /adriapi