name: AdriAPI
version: '${project.version}'
main: me.adrigamer2950.adriapi.AdriAPI
api-version: 1.16
author: Adrigamer2950
description: An API created to simplify spigot plugin development to make it easy
website: https://github.com/Adrigamer2950/AdriAPI

commands:
  adriapi:
    description: Main command
    usage: /adriapi