name: Build

on:
  push:

env:
  COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"

jobs:
  build:
    if: github.repository == 'Adrigamer2950/Obsidian'
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
        name: Checkout sources

      - uses: actions/setup-java@v5
        name: Set up JDK 17
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        name: Setup Gradle

      - name: Build Artifact
        run: "chmod +x ./gradlew && ./gradlew build"

      - uses: actions/upload-artifact@v4
        name: Save Artifact
        with:
          name: "Obsidian-b${{ github.run_number }}"
          path: build/libs/*.jar

      - name: Publish Artifact
        env:
          NEXUS_USERNAME: "${{ secrets.NEXUS_USERNAME }}"
          NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"
        run: "./gradlew :core:publish -PNEXUS_USERNAME=$NEXUS_USERNAME -PNEXUS_PASSWORD=$NEXUS_PASSWORD"