name: Build & Publish

on: [
  workflow_dispatch,
  push
]

env:
  BUILD_NUMBER: "${{ github.run_number }}"
  COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: Checkout sources

      - uses: actions/setup-java@v4
        name: Set up JDK 17
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        name: Setup Gradle

      - name: Build Artifact
        run: "chmod +x ./gradlew && ./gradlew build $([[ \"$COMMIT_MESSAGE\" == \"release:\"* ]] && echo || echo -PBUILD_NUMBER=$BUILD_NUMBER)"

      - uses: actions/upload-artifact@v4
        name: Save Artifact
        with:
          name: "AdriAPI-b${{ github.run_number }}"
          path: build/libs/*.jar

      - name: Publish Artifact
        if: github.repository == 'Adrigamer2950/AdriAPI'
        env:
          NEXUS_USERNAME: "${{ secrets.NEXUS_USERNAME }}"
          NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"
        run: "./gradlew publish -PNEXUS_USERNAME=$NEXUS_USERNAME -PNEXUS_PASSWORD=$NEXUS_PASSWORD $([[ \"$COMMIT_MESSAGE\" == \"release:\"* ]] && echo \"\" || echo \"-PBUILD_NUMBER=$BUILD_NUMBER\")"
  publish:
    if: ${{ github.repository == 'Adrigamer2950/AdriAPI' && startsWith(github.event.head_commit.message, 'release:') }}
    name: Publish Release
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: Checkout sources

      - uses: actions/setup-java@v4
        name: Set up JDK 17
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        name: Setup Gradle

      - name: Create gh-assets directory
        run: "mkdir gh-assets"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: "AdriAPI-b${{ github.run_number }}"
          path: "./gh-assets"

      - name: "Extract jar file from artifact"
        run: |
          cd gh-assets
          DIR_NAME=$(ls -1 | head -n 1)
          mv $DIR_NAME/* .
          rm -rf $DIR_NAME
          cd ..

      - name: Publish to HangarMC
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
        run: "chmod +x ./gradlew && ./gradlew publishPluginPublicationToHangar"

      - name: Publish to Modrinth
        env:
          MODRINTH_TOKEN: "${{ secrets.MODRINTH_TOKEN }}"
        run: "./gradlew modrinth modrinthSyncBody"