name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      file:
        description: 'The file to publish'
        required: true
        default: 'build/libs/AdriAPI-*.jar'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Fetch release asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'Adrigamer2950/AdriAPI'
          file: ${{ inputs.file }}

      - run: "echo $(ls)"