name: Publish

on:
  - workflow_dispatch

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: Checkout sources

      - uses: actions/setup-java@v4
        name: Set up JDK 17
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        name: Setup Gradle

      - name: Publish to HangarMC
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
        run: "chmod +x ./gradlew && ./gradlew publishPluginPublicationToHangar"

      - name: Publish to Modrinth
        env:
          MODRINTH_TOKEN: "${{ secrets.MODRINTH_TOKEN }}"
        run: "./gradlew modrinth modrinthSyncBody"